//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workflow.Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;hyperVolume version=&quot;3&quot; description=&quot;Invalid hyper volume&quot; pollingTime=&quot;0&quot;&gt;
        ///   &lt;invalidTag/&gt;
        ///&lt;/hyperVolume&gt;.
        /// </summary>
        internal static string invalid_hv {
            get {
                return ResourceManager.GetString("invalid_hv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;hyperVolume version=&quot;3&quot; description=&quot;Test hyper volume&quot; pollingTime=&quot;0&quot;&gt;&lt;label lang=&quot;default&quot;&gt;&lt;/label&gt;&lt;filter enabled=&quot;1&quot; sequenceNumber=&quot;1&quot; versioningEnabled=&quot;0&quot; updateAttachmentEnabled=&quot;0&quot; cadesEnabled=&quot;0&quot; padesEnabled=&quot;0&quot; padesMassiveEnabled=&quot;0&quot; cadesAttachmentEnabled=&quot;0&quot; padesAttachmentEnabled=&quot;0&quot; viewVersionsEnabled=&quot;0&quot;&gt;&lt;conditions&gt;&lt;notEqual enabled=&quot;1&quot;&gt;&lt;field&gt;DESCRIPT&lt;/field&gt;&lt;constant&gt;&lt;/constant&gt;&lt;/notEqual&gt;&lt;/conditions&gt;&lt;localizedDescription lang=&quot;default&quot;&gt;Non e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_hv {
            get {
                return ResourceManager.GetString("test_hv", resourceCulture);
            }
        }
    }
}
